apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kqthi6urj-nodejs 
  janus-idp.io/tekton: kqthi6urj-nodejs
  backstage.io/kubernetes-id: kqthi6urj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kqthi6urj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  